// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	coreHealth: () => typedError<HealthSnapshot, AppError>(__TAURI_INVOKE("core_health")),
	appSettings: () => typedError<AppSettings, AppError>(__TAURI_INVOKE("app_settings")),
	updateAppSettings: (request: UpdateAppSettingsRequest) => typedError<ActionReceipt<AppSettings>, AppError>(__TAURI_INVOKE("update_app_settings", { request })),
	listPermissionPolicies: () => typedError<PermissionPolicy[], AppError>(__TAURI_INVOKE("list_permission_policies")),
	upsertPermissionPolicy: (request: UpsertPermissionPolicyRequest) => typedError<ActionReceipt<PermissionPolicy>, AppError>(__TAURI_INVOKE("upsert_permission_policy", { request })),
	listCredentialReferences: () => typedError<CredentialReference[], AppError>(__TAURI_INVOKE("list_credential_references")),
	saveCredential: (request: SaveCredentialRequest) => typedError<ActionReceipt<CredentialReference>, AppError>(__TAURI_INVOKE("save_credential", { request })),
	revokeCredential: (request: RevokeCredentialRequest) => typedError<ActionReceipt<CredentialReference>, AppError>(__TAURI_INVOKE("revoke_credential", { request })),
	listAreas: () => typedError<Area[], AppError>(__TAURI_INVOKE("list_areas")),
	listGoals: () => typedError<Goal[], AppError>(__TAURI_INVOKE("list_goals")),
	listProjects: () => typedError<Project[], AppError>(__TAURI_INVOKE("list_projects")),
	listArchivedProjects: () => typedError<Project[], AppError>(__TAURI_INVOKE("list_archived_projects")),
	listTrashedProjects: () => typedError<Project[], AppError>(__TAURI_INVOKE("list_trashed_projects")),
	listArchivedGoals: () => typedError<Goal[], AppError>(__TAURI_INVOKE("list_archived_goals")),
	listTrashedGoals: () => typedError<Goal[], AppError>(__TAURI_INVOKE("list_trashed_goals")),
	listTrashedAreas: () => typedError<Area[], AppError>(__TAURI_INVOKE("list_trashed_areas")),
	listArchivedAreas: () => typedError<Area[], AppError>(__TAURI_INVOKE("list_archived_areas")),
	createArea: (request: CreateAreaRequest) => typedError<ActionReceipt<Area>, AppError>(__TAURI_INVOKE("create_area", { request })),
	createGoal: (request: CreateGoalRequest) => typedError<ActionReceipt<Goal>, AppError>(__TAURI_INVOKE("create_goal", { request })),
	createProject: (request: CreateProjectRequest) => typedError<ActionReceipt<Project>, AppError>(__TAURI_INVOKE("create_project", { request })),
	updateProject: (request: UpdateProjectRequest) => typedError<ActionReceipt<Project>, AppError>(__TAURI_INVOKE("update_project", { request })),
	archiveProject: (request: AreaLifecycleRequest) => typedError<ActionReceipt<Project>, AppError>(__TAURI_INVOKE("archive_project", { request })),
	trashProject: (request: AreaLifecycleRequest) => typedError<ActionReceipt<Project>, AppError>(__TAURI_INVOKE("trash_project", { request })),
	restoreProject: (request: AreaLifecycleRequest) => typedError<ActionReceipt<Project>, AppError>(__TAURI_INVOKE("restore_project", { request })),
	updateGoal: (request: UpdateGoalRequest) => typedError<ActionReceipt<Goal>, AppError>(__TAURI_INVOKE("update_goal", { request })),
	archiveGoal: (request: AreaLifecycleRequest) => typedError<ActionReceipt<Goal>, AppError>(__TAURI_INVOKE("archive_goal", { request })),
	trashGoal: (request: AreaLifecycleRequest) => typedError<ActionReceipt<Goal>, AppError>(__TAURI_INVOKE("trash_goal", { request })),
	restoreGoal: (request: AreaLifecycleRequest) => typedError<ActionReceipt<Goal>, AppError>(__TAURI_INVOKE("restore_goal", { request })),
	updateArea: (request: UpdateAreaRequest) => typedError<ActionReceipt<Area>, AppError>(__TAURI_INVOKE("update_area", { request })),
	archiveArea: (request: AreaLifecycleRequest) => typedError<ActionReceipt<Area>, AppError>(__TAURI_INVOKE("archive_area", { request })),
	trashArea: (request: AreaLifecycleRequest) => typedError<ActionReceipt<Area>, AppError>(__TAURI_INVOKE("trash_area", { request })),
	restoreArea: (request: AreaLifecycleRequest) => typedError<ActionReceipt<Area>, AppError>(__TAURI_INVOKE("restore_area", { request })),
	areaHistory: (request: AreaHistoryRequest) => typedError<AreaVersion[], AppError>(__TAURI_INVOKE("area_history", { request })),
	auditEntries: (request: AuditListRequest) => typedError<AuditEntry[], AppError>(__TAURI_INVOKE("audit_entries", { request })),
	undoAction: (request: UndoRequest) => typedError<ActionReceipt<UndoResult>, AppError>(__TAURI_INVOKE("undo_action", { request })),
	searchEntities: (request: SearchRequest) => typedError<SearchResult[], AppError>(__TAURI_INVOKE("search_entities", { request })),
	foundationCheck: () => typedError<HealthSnapshot, AppError>(__TAURI_INVOKE("foundation_check")),
};

/** Events */
export const events = {
	foundationProgress: makeEvent<FoundationProgress>("foundation-progress"),
};

/* Types */
export type ActionReceipt<T> = {
	data: T,
	operationId: string,
	affectedEntityIds: string[],
	resultingRevisions: EntityRevision[],
	domainEventIds: string[],
	undoBatchId: string | null,
};

export type ActorKind = "user" | "ai" | "mcp" | "automation" | "obsidian";

export type AppError = { code: "VALIDATION"; details: {
	field: string,
	reason: string,
} } | { code: "NOT_FOUND"; details: {
	entityId: string,
} } | { code: "CONFLICT_REVISION"; details: {
	entityId: string,
	expected: number,
	actual: number,
} } | { code: "CONFLICT_EXTERNAL"; details: {
	reason: string,
} } | { code: "INTEGRITY_FAILURE"; details: {
	reason: string,
} } | { code: "PERMISSION_DENIED"; details: {
	operation: string,
} } | { code: "CONFIRMATION_REQUIRED"; details: {
	operation: string,
} } | { code: "UNAVAILABLE"; details: {
	service: string,
} } | { code: "INTERNAL"; details: {
	operationId: string,
} };

export type AppSettings = {
	locale: string,
	theme: ThemePreference,
	timezone: string,
	weekStartsOn: number,
	revision: number,
};

export type Area = {
	id: string,
	title: string,
	revision: number,
	createdAtMs: string,
	updatedAtMs: string,
	archivedAtMs: string | null,
	deletedAtMs: string | null,
};

export type AreaHistoryRequest = {
	id: string,
	limit: number,
};

export type AreaLifecycleRequest = {
	id: string,
	expectedRevision: number,
	operationId: string,
};

export type AreaVersion = {
	revision: number,
	title: string,
	operationId: string,
	createdAtMs: string,
};

/**
 *  A deliberately narrow audit projection for the user-facing timeline.
 *  Sensitive audit payloads, entity lists, and internal operation identifiers
 *  stay inside Rust Core; callers receive only safe, display-oriented metadata.
 */
export type AuditEntry = {
	id: string,
	action: string,
	actorKind: ActorKind,
	occurredAtMs: string,
};

export type AuditListRequest = {
	limit: number,
};

export type CreateAreaRequest = {
	title: string,
	operationId: string,
};

export type CreateGoalRequest = {
	title: string,
	horizon: GoalHorizon,
	startDate: string | null,
	targetDate: string | null,
	operationId: string,
};

export type CreateProjectRequest = {
	title: string,
	parentProjectId: string | null,
	priority: number | null,
	startDate: string | null,
	targetDate: string | null,
	operationId: string,
};

export type CredentialReference = {
	id: string,
	kind: string,
	revision: number,
	revokedAtMs: string | null,
};

export type EntityRevision = {
	entityId: string,
	revision: number,
};

export type FoundationProgress = {
	phase: string,
	percent: number,
};

export type Goal = {
	id: string,
	title: string,
	horizon: GoalHorizon,
	status: string,
	startDate: string | null,
	targetDate: string | null,
	revision: number,
	createdAtMs: string,
	updatedAtMs: string,
	archivedAtMs: string | null,
	deletedAtMs: string | null,
};

export type GoalHorizon = "short" | "medium" | "long" | "lifetime";

export type HealthSnapshot = {
	schemaVersion: number,
	sqliteVersion: string,
	journalMode: string,
	foreignKeysEnabled: boolean,
};

export type PermissionDecision = "allow" | "ask" | "deny";

export type PermissionPolicy = {
	id: string,
	subjectKind: ActorKind,
	operation: string,
	decision: PermissionDecision,
	enabled: boolean,
	revision: number,
};

export type Project = {
	id: string,
	title: string,
	parentProjectId: string | null,
	status: string,
	priority: number | null,
	startDate: string | null,
	targetDate: string | null,
	revision: number,
	createdAtMs: string,
	updatedAtMs: string,
	archivedAtMs: string | null,
	deletedAtMs: string | null,
};

export type RevokeCredentialRequest = {
	id: string,
	expectedRevision: number,
	operationId: string,
};

export type SaveCredentialRequest = {
	kind: string,
	secret: string,
	operationId: string,
};

export type SearchRequest = {
	query: string,
	prefix: boolean,
};

export type SearchResult = {
	entityId: string,
	title: string,
	score: number | null,
};

export type ThemePreference = "light" | "dark" | "system";

export type UndoRequest = {
	undoBatchId: string,
	operationId: string,
};

export type UndoResult = {
	undoneUndoBatchId: string,
	entityId: string,
	revision: number,
};

export type UpdateAppSettingsRequest = {
	locale: string,
	theme: ThemePreference,
	timezone: string,
	weekStartsOn: number,
	expectedRevision: number,
	operationId: string,
};

export type UpdateAreaRequest = {
	id: string,
	title: string,
	expectedRevision: number,
	operationId: string,
};

export type UpdateGoalRequest = {
	id: string,
	title: string,
	horizon: GoalHorizon,
	startDate: string | null,
	targetDate: string | null,
	expectedRevision: number,
	operationId: string,
};

export type UpdateProjectRequest = {
	id: string,
	title: string,
	priority: number | null,
	startDate: string | null,
	targetDate: string | null,
	expectedRevision: number,
	operationId: string,
};

export type UpsertPermissionPolicyRequest = {
	subjectKind: ActorKind,
	operation: string,
	decision: PermissionDecision,
	enabled: boolean,
	expectedRevision: number | null,
	operationId: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

