// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	coreHealth: () => typedError<HealthSnapshot, AppError>(__TAURI_INVOKE("core_health")),
	listAreas: () => typedError<Area[], AppError>(__TAURI_INVOKE("list_areas")),
	createArea: (request: CreateAreaRequest) => typedError<ActionReceipt<Area>, AppError>(__TAURI_INVOKE("create_area", { request })),
	updateArea: (request: UpdateAreaRequest) => typedError<ActionReceipt<Area>, AppError>(__TAURI_INVOKE("update_area", { request })),
	undoAction: (request: UndoRequest) => typedError<ActionReceipt<UndoResult>, AppError>(__TAURI_INVOKE("undo_action", { request })),
	searchEntities: (request: SearchRequest) => typedError<SearchResult[], AppError>(__TAURI_INVOKE("search_entities", { request })),
	foundationCheck: () => typedError<HealthSnapshot, AppError>(__TAURI_INVOKE("foundation_check")),
};

/** Events */
export const events = {
	foundationProgress: makeEvent<FoundationProgress>("foundation-progress"),
};

/* Types */
export type ActionReceipt<T> = {
	data: T,
	operationId: string,
	affectedEntityIds: string[],
	resultingRevisions: EntityRevision[],
	domainEventIds: string[],
	undoBatchId: string | null,
};

export type AppError = { code: "VALIDATION"; details: {
	field: string,
	reason: string,
} } | { code: "NOT_FOUND"; details: {
	entity_id: string,
} } | { code: "CONFLICT_REVISION"; details: {
	entity_id: string,
	expected: number,
	actual: number,
} } | { code: "INTEGRITY_FAILURE"; details: {
	reason: string,
} } | { code: "INTERNAL"; details: {
	operation_id: string,
} };

export type Area = {
	id: string,
	title: string,
	revision: number,
	createdAtMs: string,
	updatedAtMs: string,
};

export type CreateAreaRequest = {
	title: string,
	operationId: string,
};

export type EntityRevision = {
	entityId: string,
	revision: number,
};

export type FoundationProgress = {
	phase: string,
	percent: number,
};

export type HealthSnapshot = {
	schemaVersion: number,
	sqliteVersion: string,
	journalMode: string,
	foreignKeysEnabled: boolean,
};

export type SearchRequest = {
	query: string,
	prefix: boolean,
};

export type SearchResult = {
	entityId: string,
	title: string,
	score: number | null,
};

export type UndoRequest = {
	undoBatchId: string,
	operationId: string,
};

export type UndoResult = {
	undoneUndoBatchId: string,
	entityId: string,
	revision: number,
};

export type UpdateAreaRequest = {
	id: string,
	title: string,
	expectedRevision: number,
	operationId: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

