// This file has been generated by TauRPC. Do not edit this file manually.


import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult, type UnlistenFn } from 'taurpc'
export type Area = {
	id: string,
	title: string,
	revision: number,
};

export type FoundationProgress = {
	phase: string,
	percent: number,
};

export type ProbeError = { code: "NOT_FOUND"; details: {
	entityId: string,
} } | { code: "CONFLICT_REVISION"; details: {
	expected: number,
	actual: number,
} };

export type Result<T, E> = {
	ok: T,
	err: E,
};

export type UpdateAreaRequest = {
	id: string,
	title: string,
	expectedRevision: number,
};
const ARGS_MAP = {"":{"foundation_progress":["progress"],"get_area":["id"],"update_area":["request"]}};

const RESULT_MAP = {"":{"foundation_progress":false,"get_area":true,"update_area":true}};

export type Router = {
	"": {
		foundation_progress: { on: (listener: (progress: FoundationProgress) => void) => Promise<UnlistenFn> },
		get_area: (id: string) => Promise<TauRpcResult<Area, ProbeError>>,
		update_area: (request: UpdateAreaRequest) => Promise<TauRpcResult<Area, ProbeError>>,
	},
};
export const createTauRPCProxy = () => createProxy<Router>({
  argsMap: ARGS_MAP,
  resultMap: RESULT_MAP,
  errorHandling: "result",
})

// export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput, TauRpcResult }
